### ISSUE TITLE
[14.0] account_asset_management, improvements for more use cases

### ISSUE THREAD

**Issue by kittiu** [OCA/account-financial-tools#1226]
This issue is created to consolidate the improvement of asset management module. The existing account_asset_management is good but still not cover our case. In some project, we deal with big number of asset and its dynamism. For instance, we need to cover cases like,

**Use Cases (not capable with current module)**

* Adopt asset donated by other party.
* Remove multiple assets at the same time.
* Asset Under Construction (AUC), which do not run depreciation by itself, but need to change to normal asset (can be many AUC to a new Asset).
* Asset profile with no depreciation table.
* Combining many asset(s) into one new asset. (or constructing a new asset from existing assets)
* Asset that gone through big revamp which may add value and useful life to asset.
* Ability to stop deprecitation, in order to sell it later (asset held for sale).
* Change owner of the asset (i.e.., change analytic). Then the financial report should reflect upon it.
* ???

Some discussion and work already done which may already cover cases, I will just list them here.

**PRs:**

- [x] https://github.com/OCA/account-financial-tools/pull/1231
- [ ] https://github.com/OCA/account-financial-tools/pull/1208
- [x] https://github.com/OCA/account-financial-tools/pull/1232
- [ ] https://github.com/OCA/account-financial-tools/pull/1044

**Discuss:**

* https://odoo-community.org/groups/contributors-15/contributors-166636?mode=thread&date_begin=&date_end=

---

**TODO**

Based on above use cases, we plan to address them by following development.

- [x] Asset Profile with No Depreciation (account_asset_management_no_depreciation)
- [ ] Review Asset Depreciation Table manual edit, ability to stop deprecitation, in order to sell it later (asset held for sale) (account_asset_management)
- [x] Asset Transfer (account_asset_management_transfer)
  * Merge (many asset to one)
  * Split (one asset to many)
  * Transfer (many to many)
- [ ] Asset Reports
  * Columns: code, name, location, doc no., date purchase, start depreciation, cost value, salvage value, depre rate / useful life, depre amount (per period), depre this period, cost remaining, state (running, removed, stop depre), removal date.
