### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-tools#1472]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_asset_management - By @RodrigoBM - #1479
- [ ] account_asset_management_menu
- [x] ~~account_balance_line~~ Included in core
- [x] account_bank_statement_chatter - By @sergiobstoj - #1869
- [x] account_chart_update - By @ljsalvatierra-factorlibre - #1555
- [ ] account_check_deposit - By @fanchlegal - #1907
- [x] account_fiscal_month - By @BT-anieto - #1708
- [x] account_fiscal_position_vat_check - By @syera94 - #1480
- [x] account_fiscal_year - By @baimont - #1473
- [x] account_fiscal_year_auto_create - By @legalsylvain - #1492
- [x] account_invoice_constraint_chronology - By @AnizR - #1474
- [x] account_journal_general_sequence - By @yajo - #1536
- [x] account_journal_lock_date - By @RodrigoBM - #1509
- [x] account_loan - By @etobella - #1721
- [ ] account_lock_date_update
- [ ] account_maturity_date_default
- [ ] account_move_budget
- [x] ~~account_move_force_removal~~ Not needed anymore. See odoo/odoo@6112f4f
- [x] account_move_fiscal_month - By @BT-anieto - #1709
- [x] account_move_fiscal_year - By @BT-anieto - #1710
- [x] account_move_line_landed_cost_info - By @AlexPForgeFlow - #1720
- [ ] ~account_move_line_menu~ - Deprecated, see https://github.com/OCA/account-financial-tools/issues/1472#issuecomment-1469789675 
- [x] account_move_line_purchase_info - By @astirpe - #1616
- [ ] account_move_line_sale_info
- [x] account_move_line_tax_editable - By @ljsalvatierra-factorlibre - #1508
- [x] account_move_name_sequence - By @RodrigoBM - #1510
- [x] account_move_print - By @ramiadavid - #1481
- [ ] account_move_template
- [x] account_move_transfer_partner - By @AlexPForgeFlow - #1736
- [x] account_partner_required - By @alexis-via - #1542
- [x] account_sequence_option - By @Saran440 - #1810
- [x] account_template_active - By @legalsylvain - #1491
- [x] account_usability - By @legalsylvain - #1477
- [x] base_vat_optional_vies - By @RodrigoBM - #1572
- [ ] product_category_tax
- [ ] sale_unreconciled - By @AaronHForgeFlow - #1936

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by RodrigoBM** [comment]
I will work on account_asset_management

**Comment by rafaelbn** [comment]
account_balance_line not needed any more: https://github.com/OCA/account-financial-tools/pull/1476#issuecomment-1271683038

Is it a procedure to indicate it here an in OpenUpgrade?

**Comment by pedrobaeza** [comment]
Here it's strikethrough and indicated that is not needed. On OpenUpgrade the module can be indicated as merged in apriori file for smoother migration.

**Comment by RodrigoBM** [comment]
Why is account_fiscal_year and account_invoice_constraint_chronology not checked on the list?

**Comment by pedrobaeza** [comment]
It's not done automatically. See https://github.com/OCA/oca-github-bot/issues/189 and https://github.com/OCA/oca-github-bot/pull/192 and you can review for getting this feature.

**Comment by RodrigoBM** [comment]
thanks for the info @pedrobaeza

**Comment by ramiadavid** [comment]
Hi @sbidoul 

Im working in `account_move_print` #1481

**Comment by ljsalvatierra-factorlibre** [comment]
Hi

I'm currently working on migrating `account_move_line_tax_editable`

--
https://github.com/OCA/account-financial-tools/pull/1508

**Comment by RodrigoBM** [comment]
PR [account_move_name_sequence](https://github.com/OCA/account-financial-tools/pull/1510)

**Comment by RodrigoBM** [comment]
PR  [account_journal_lock_date](https://github.com/OCA/account-financial-tools/pull/1509)

**Comment by ljsalvatierra-factorlibre** [comment]
Hi

I'm currently working on migrating `account_chart_update`

---

https://github.com/OCA/account-financial-tools/pull/1555

**Comment by ljsalvatierra-factorlibre** [comment]
Hi

I'm currently working on migratin `account_chart_update_l10n_eu_oss`

---

https://github.com/OCA/account-financial-tools/pull/1556

**Comment by BT-atornero** [comment]
I'm migrating ```account_group_menu``` #1563

**Comment by RodrigoBM** [comment]
I'm migrating base_vat_optional_vies #1572

**Comment by JavierIniesta** [comment]
Hi!

I'm currently working on migrating `account_asset_batch_compute`.

PR: #1611

**Comment by astirpe** [comment]
Module `account_move_line_menu` seems not necessary anymore, since the menuitem for Journal Entries is now accessible to group `group_account_readonly` in Odoo 16 (after commit https://github.com/odoo/odoo/commit/f5541768a6af90565de79e782d39643b9f5bfc11)

**Comment by astirpe** [comment]
`account_move_line_purchase_info` https://github.com/OCA/account-financial-tools/pull/1616 and `account_move_line_sale_info` https://github.com/OCA/account-financial-tools/pull/1617

**Comment by astirpe** [comment]
Module `account_move_force_removal` seems not necessary anymore for V16. The module was basically just bypassing the check made in method `_unlink_forbid_parts_of_chain()` that was ensuring that the sequence number was the last element of a chain of sequence. In V16 that method was removed, see https://github.com/odoo/odoo/commit/6112f4f59aeb5dc5a3b698edd861b19f25da7017

**Comment by pedrobaeza** [comment]
> Module `account_move_force_removal` seems not necessary anymore for V16. The module was basically just bypassing the check made in method `_unlink_forbid_parts_of_chain()` that was ensuring that the sequence number was the last element of a chain of sequence. In V16 that method was removed, see [odoo/odoo@6112f4f](https://github.com/odoo/odoo/commit/6112f4f59aeb5dc5a3b698edd861b19f25da7017)

Handled in https://github.com/OCA/OpenUpgrade/pull/3802

**Comment by jaenbox** [comment]
Migration account_move_budget #1658

**Comment by ghost** [comment]
Hi,

Currently working on account_asset_number: https://github.com/OCA/account-financial-tools/pull/1687

**Comment by BT-anieto** [comment]
I'm missing **account_fiscal_month**, **account_move_fiscal_month** and **account_move_fiscal_year**

I'm working on them:
account_fiscal_month: #1708
account_move_fiscal_month #1709 
account_move_fiscal_year #1710

**Comment by SirAionTech** [comment]
Migrating **account_lock_to_date** in https://github.com/OCA/account-financial-tools/pull/1732

**Comment by FreezeS** [comment]
Hi guys,

Anyone working on migrating product_category_tax?

**Comment by astirpe** [comment]
@FreezeS product_category_tax V16 is here: https://github.com/OCA/account-financial-tools/pull/1618
But we don't need this module anymore, so I will be happy if you or someone else will take over this PR..

**Comment by matteoopenf** [comment]
account_sequence_option https://github.com/OCA/account-financial-tools/pull/1775

**Comment by matteoopenf** [comment]
mig  https://github.com/OCA/account-financial-tools/pull/1776  account_move_force_removal

**Comment by FreezeS** [comment]
@astirpe why don't we need product_category_tax, has the functionality been implemented somewhere else? I see that #1618 has been closed.

**Comment by astirpe** [comment]
@FreezeS we don't need `product_category_tax` for our projects anymore, maybe you or someone else can take over...

**Comment by fanchlegal** [comment]
Hi

I'm currently working on migrating account_check_deposit #1907

**Comment by metaminux** [comment]
> Hi
> 
> I'm currently working on migrating account_check_deposit [#1907](https://github.com/OCA/account-financial-tools/pull/1907)

Hi everyone,

@sbidoul Can you add account_check_deposit in the list of modules to migrate ?

@fanchlegal opened PR #1907 (still open) and @alexis-via opened #1529 (closed because integration of improvements from #872 were required by @legalsylvain - see https://github.com/OCA/account-financial-tools/pull/1529#issuecomment-2587898953)
