### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-tools#311]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] account_asset_depr_line_cancel - By @chienandalu - #490 
- [ ] account_asset_management
- [ ] account_asset_management_xls
- [x] ~~account_auto_fy_sequence~~ - Not needed anymore - #321 
- [ ] account_balance_line
- [ ] account_cancel_invoice_check_payment_order
- [ ] account_cancel_invoice_check_voucher
- [x] account_chart_update - ~~By @Yajo - #381~~ - By @jbaudoux - #420 
- [ ] account_check_deposit
- [ ] account_compute_tax_amount
- [ ] account_constraints @vrenaville 
- [ ] account_credit_control
- [ ] account_credit_control_dunning_fees
- [ ] account_default_draft_move
  - the Skip Draft State (aka entry_posted) journal option does not exist in 9.0
- [x] account_fiscal_position_vat_check - By @cubells - #418 
- [ ] account_invoice_constraint_chronology
- [x] account_invoice_currency - By @antespi - #390 
- [x] account_invoice_tax_required - By @angelmoya - #404 
- [ ] account_journal_always_check_date
- [ ] account_journal_period_close
  - since periods are gone, the underlying infrastructure that allowed fined grained closing per journal is gone too and is replaced by a per company lock date
- [ ] account_move_batch_validate - By @oleksandrpaziuk - #602 
- [ ] account_move_line_no_default_search
- [ ] account_move_line_payable_receivable_filter
- [ ] account_move_line_search_extension
- [x] account_move_locking 
  - [ ] some fixes @mdietrichc2c #377
- [ ] account_move_template
- [ ] account_partner_required
- [ ] account_renumber - By @Yajo - #379 
- [ ] account_reset_chart
- [x] account_reversal - By @antespi - #405 
  - Reverse Move is standard in 9.0 Community
  - The to_reverse flag and link to reversal move are missing in 9.0 so an OCA module can add that
- [ ] account_tax_analysis @vrenaville 
- [ ] account_tax_chart_interval
- [ ] account_tax_update
- [ ] async_move_line_importer
- [ ] currency_rate_date_check
- [x] currency_rate_update  #318 by @vrenaville and @yvaucher (includes refactor #363 @katyukha )
- [ ] account_reconcile_trace

**Comment by vrenaville** [comment]
@yvaucher I currently work on account_tax_analysis for V9

**Comment by yvaucher** [comment]
@vrenaville Thanks I added you, let me know where a PR is opened I'll add the link

**Comment by vrenaville** [comment]
@yvaucher I will also migrate account_constraints

**Comment by yvaucher** [comment]
updated

**Comment by yajo** [comment]
I'm starting work to migrate `account_renumber`.

**Comment by ghost** [comment]
#318 merged
