### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-tools#406]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] account_asset_depr_line_cancel - By @chienandalu - #488 
- [ ] account_asset_management - By @adrienpeiffer - #441
- [ ] account_asset_management_xls
- [x] ~~account_auto_fy_sequence~~ - Not needed anymore
- [x] account_balance_line - By @mourad-ehm - #468 
- [ ] account_cancel_invoice_check_payment_order
- [ ] account_cancel_invoice_check_voucher
- [x] account_chart_update - By @sylvainvh - #460 
- [ ] account_check_deposit
- [ ] account_constraints - By @mourad-ehm - #469 
- [x] account_credit_control - By @sylvainvh - #462 
- [ ] account_credit_control_dunning_fees
- [ ] account_default_draft_move
- [x] account_fiscal_position_vat_check - By @alexis-via - #408
- [x] account_fiscal_year - By @espo-tony - #407 
- [ ] account_invoice_constraint_chronology - By @GillesTephaneMeyomesse - #457
- [x] account_invoice_currency - @seb4itik - By #443 
- [x] account_invoice_tax_required - By @kittiu - #484 
- [ ] account_journal_always_check_date
- [x] account_journal_period_close > account_journal_lock_date - @sbidoul in #471
- [x] account_move_batch_validate - By @benwillig - #510 
- [ ] account_move_line_no_default_search - Not needed on v10
- [ ] account_move_line_payable_receivable_filter - By @mourad-ehm - #470 
- [ ] account_move_line_search_extension - Not needed on v10
- [ ] account_move_locking
- [ ] account_move_template - By @nhomar - #511 
- [x] account_netting - By @cubells - #556 
- [ ] account_partner_required - By @alexis-via - #426 
- [x] account_permanent_lock_move - By @adrienpeiffer - #410 
- [x] account_renumber - By @chienandalu - #517 
- [ ] account_reset_chart
- [x] account_reversal - By @Cedric-Pigeon - #445 
- [x] ~~account_tax_analysis~~ - Replaced by account_tax_balance (in OCA/account-financial-reporting)
- [x] ~~account_tax_chart_interval~~ - Feature has disappeared in core
- [ ] account_tax_update
- [ ] async_move_line_importer
- [x] base_vat_optional_vies - By @chienandalu - #507 
- [ ] currency_rate_date_check
- [x] currency_rate_update - By @nikiwaibel - #415

**Comment by kittiu** [comment]
@pedrobaeza can I help upgrade account_auto_fy_sequence? (I use it regularly)

**Comment by pedrobaeza** [comment]
That one is not needed anymore since v9. It should be removed from this branch

**Comment by sbidoul** [comment]
@pedrobaeza @kittiu the PR to remove it from 9.0 is pending since a long time: https://github.com/OCA/account-financial-tools/pull/321

**Comment by pedrobaeza** [comment]
Yeah, and I suggested the migration script :wink:

**Comment by kittiu** [comment]
Noted!

**Comment by pedrobaeza** [comment]
I already did the script: https://github.com/OCA/OpenUpgrade/commit/b19f359b82b3da506e0ce16544b4ff395f44262f, so I remove the module.
