### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-tools#551]
Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_asset_depr_line_cancel
- [ ] account_asset_disposal - By @pedrobaeza - #736 
- [x] account_asset_management - By @grindtildeath - #698 
- [ ] account_asset_management_method_number_end - By @grindtildeath - #704 
- [ ] account_asset_management_xls - By @luc-demeyer - #701
- [x] account_balance_line - By @rruebner - #645 
- [ ] account_cancel_invoice_check_payment_order
- [ ] account_cancel_invoice_check_voucher
- [x] account_chart_update - By @amcor - #658 
- [x] account_check_deposit - By @pedrobaeza - #678 
- [ ] account_constraints
- [x] account_credit_control - By @kenvac - #603 
- [x] account_credit_control_dunning_fees - By @grindtildeath - #607 
- [ ] account_default_draft_move
- [ ] account_fiscal_month - By @feketemihai - #636 
- [x] account_fiscal_position_vat_check - ~~By @carlosDomatix - #578~~ - By @rven - #681 
- [x] account_fiscal_year - By @jbeficent - #592 
- [x] account_invoice_constraint_chronology - ~~By @OpenCode - #590~~ - By @rgarnau - #600 
- [x] account_invoice_currency - By @Softdil - #644 
- [x] account_invoice_tax_required - Moved to OCA/account-invoicing#329
- [ ] account_journal_always_check_date
- [ ] account_journal_lock_date - By @feketemihai - #615 
- [x] account_lock_date_update - By @feketemihai - #612 
- [x] account_move_batch_validate - ~~By @oleksandrpaziuk - #597~~ By @grindtildeath - #723 
- [ ] account_move_fiscal_month - By @feketemihai - #637 
- [x] account_move_fiscal_year - By @feketemihai - #638 
- [ ] account_move_line_no_default_search
- [ ] account_move_line_payable_receivable_filter
- [x] account_move_line_purchase_info - By @lreficent - #609 
- [ ] account_move_line_search_extension
- [x] account_move_line_tax_editable - By @feketemihai - #630 
- [ ] account_move_locking - By @feketemihai - #615 
- [ ] account_move_template - ~~By @rven - #626~~ By @jbeficent - #728 
- [x] account_netting - By @feketemihai - #606 
- [x] account_partner_required - By @rven - #622 
- [ ] account_permanent_lock_move - By @feketemihai - #615 
- [ ] account_permanent_lock_move_update - By @feketemihai - #615 
- [x] account_renumber - By @AbrahamTrey - #577 
- [ ] account_reset_chart
- [x] account_reversal - by @jbeficent - #568 
- [ ] account_tax_analysis - By @sbidoul - #660 
- [ ] account_tax_update
- [ ] account_type_inactive
- [x] account_type_menu - By @arkostyuk - #586 
- [ ] async_move_line_importer
- [ ] base_vat_optional_vies
- [ ] currency_rate_date_check
- [x] currency_rate_update - By @jesusVMayor and @jbeficent - Moved to OCA/currency#5

**Comment by jesusVMayor** [comment]
Working on currency_rate_update

**Comment by OpenCode** [comment]
working on account_invoice_constraint_chronology

**Comment by kenvac** [comment]
working on account_credit_control

**Comment by pedrobaeza** [comment]
Noted

**Comment by astirpe** [comment]
@kenvac do you have a public branch where we can follow the developments on account_credit_control ?

**Comment by OpenCode** [comment]
@pedrobaeza account_invoice_constraint_chronology merged with PR #600

**Comment by pedrobaeza** [comment]
OK, noted

**Comment by kenvac** [comment]
@astirpe  Yes, I do have.
https://github.com/kenvac/account-financial-tools/tree/11.0-account_credit_control
I still need to work on test files

**Comment by astirpe** [comment]
@kenvac nice! I also see that all the tests are passing, IMO you could open the PR. Would you like to do it?

**Comment by kenvac** [comment]
@astirpe PR #603 created.. 😀

**Comment by feketemihai** [comment]
account_journal_lock_date
account_move_locking
account_permanent_lock_move
account_permanent_lock_move_update

comnsolidated in #615

**Comment by rven** [comment]
[11.0] [MIG] account_partner_required: Migration to 11.0 #622

**Comment by rven** [comment]
[11.0] [MIG] account_fiscal_position_vat_check: Migration to 11.0  https://github.com/OCA/account-financial-tools/pull/624

**Comment by rven** [comment]
[11.0] [MIG] account_move_template: Migration to 11.0 https://github.com/OCA/account-financial-tools/pull/626

**Comment by BeAntares** [comment]
@jesusVMayor Do you need help with the currency_rate_update module?

**Comment by OpenCode** [comment]
@pedrobaeza #586 is merged

**Comment by pedrobaeza** [comment]
OK

**Comment by feketemihai** [comment]
account_move_line_tax_editable in #630

**Comment by nadiaafa** [comment]
i would like to work on account_fiscal_month

**Comment by feketemihai** [comment]
account_fiscal_month in #636 @pedrobaeza @nadiaafa

**Comment by feketemihai** [comment]
@pedrobaeza account_lock_date_update - By @feketemihai - #615, the module is in #612 , module account_move_locking is consolidated in #615

**Comment by feketemihai** [comment]
account_move_fiscal_month in #637

**Comment by feketemihai** [comment]
account_move_fiscal_year in #638

**Comment by pedrobaeza** [comment]
OK, updated

**Comment by aitorbouzas** [comment]
account_invoice_currency in #644

**Comment by rruebner** [comment]
@pedrobaeza I created a PR 645 for account_balance_line

**Comment by rafaelbn** [comment]
@pedrobaeza should we move account_credit_control to https://github.com/OCA/credit-control ?

**Comment by pedrobaeza** [comment]
It should be moved on v12 migration

**Comment by emagdalenaC2i** [comment]
Please check in the list account_credit_control_dunning_fees because it is merged in #607 
account_move_line_purchase_info isn't in the list and is already migrated and merged in #609 
account_fiscal_position_vat_check - By @carlosDomatix - #578 is closed and superseeded by #681
account_move_template - By @rven - #626 is closed and superseded by #728 
account_asset_management_method_number_end isn't in the list and there is a PR #704 
account_tax_analysis isn't in the list and there is a PR #660

**Comment by RodrigoBM** [comment]
working on base_vat_optional_vies

**Comment by pedrobaeza** [comment]
Is that one still needed with latest versions? I'm not sure about that...

**Comment by RodrigoBM** [comment]
I think so. Because if user want to see if check_vat has been passed, we need this module.
https://github.com/OCA/account-financial-tools/issues/551#issuecomment-451460826

**Comment by pedrobaeza** [comment]
I'm still not convinced, but if you say so, then go ahead.
